#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

#include "random.h"
#include "utils.h"
#include "consts.h"
#include "codegen.h"


void verify_consts();

int main( int argc, const char* argv[] )
{

	verify_consts();
	rand_init();

	/*for (i = 0; i < values_list->size; i++) {*/
	/*printf("%s\n", values_list->liste[i]);*/
	/*}*/

	char *programmName = (char*) calloc(100, sizeof(char));
	char *programmPath = (char*) calloc(100, sizeof(char));
	char *decacCommand = (char*) calloc(100, sizeof(char));
	char *errorLine = (char*) calloc(100, sizeof(char));
	printf(decacCommand, "decac -P *.deca", programmPath);
	unsigned int nProgramm = 0;

	while((nProgramm++) < 10000) {
		
		char *programm = newProgramm();

		if (nProgramm % 100 == 0)
			printf("\n%u %%", nProgramm/100); 

		sprintf(programmName, "test_%u.deca", nProgramm);
		sprintf(programmPath, "deca/%s", programmName);

		FILE *file = fopen(programmPath, "w");
		if (file == NULL) {
			printf("\nImpossible de créer le fichier %s !", programmPath);
			return EXIT_FAILURE;
		}

		fprintf(file, "//Autogenerated programm %u\n%s", nProgramm, programm);
		
		/*FILE *stream = popen(decacCommand, "r");*/
		/*fread(errorLine, 2, 100, stream);*/

		/*if (errorLine[0] != '\0') {*/
			/*printf("valid !");*/
		/*}*/

		/*pclose(stream);*/
		fclose(file);

		free(programm);
	}

	free(programmName);
	free(programmPath);
	free(decacCommand);
	free(errorLine);

	return EXIT_SUCCESS;
}

