#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <unistd.h>
#include <dirent.h>
#include <sys/wait.h>
#include <sys/types.h>

#include "random.h"
#include "utils.h"
#include "consts.h"
#include "codegen.h"


void verify_consts();

int main( int argc, const char* argv[] )
{

	verify_consts();

	int pid;
	int *child_pids = (int*) malloc(sizeof(int)*MAX_THREADS);

	unsigned int nThread;

	for (nThread = MAX_THREADS; nThread > 0; nThread--) {
		if ((pid = fork()) != 0)
			break;

		child_pids[nThread] = pid;
	}


	/*-- CHILDS --*/
	if(nThread != 0) {
		rand_init();

		char *programmName = (char*) calloc(100, sizeof(char));
		char *programmPath = (char*) calloc(100, sizeof(char));
		char *errorLine = (char*) calloc(100, sizeof(char));
		unsigned int nProgramm = (nThread-1)*PROGRAMM_PER_THREAD;

		while((nProgramm++) < nThread*PROGRAMM_PER_THREAD) {

			char *programm = newProgramm();

			sprintf(programmName, "test_%u.deca", nProgramm);
			sprintf(programmPath, "deca/%s", programmName);

			FILE *file = fopen(programmPath, "w");
			if (file == NULL) {
				printf("\nImpossible de créer le fichier %s !", programmPath);
				return EXIT_FAILURE;
			}

			fprintf(file, "//Autogenerated programm %u\n", nProgramm);
			fprintf(file, "//Generated by thread %i\n%s", nThread, programm);

			fclose(file);

			free(programm);
		}

		free(programmName);
		free(programmPath);
		free(errorLine);
	} 
	
	/*-- MAIN --*/
	else { 
		printf("Launched %i threads, generating %i files each !\n", MAX_THREADS, PROGRAMM_PER_THREAD);

		int status;
		bool finished;

		do {
			finished = true;
			for (unsigned int i = 0; (i < MAX_THREADS) && finished; i++) {
				waitpid(child_pids[i], &status, WNOHANG);
				finished = finished && (status != 0);
				if(status == -1) {
					printf("\nError when waiting childs to terminate !\n");
					return EXIT_FAILURE;
				}
			}
			

		} while(!finished);

		printf("FINISHED !\n");
		

		/*DIR *dir;*/
		/*struct dirent *ent;*/

		/*dir = opendir("deca");*/

		/*if (dir == NULL) {*/
			/*printf("\nImpossible d'ouvrir le dossier deca !\n");*/
			/*return EXIT_FAILURE;*/
		/*}*/

	}

	free(child_pids);
	return EXIT_SUCCESS;
}

